services:
  db:
    container_name: workout-db
    image: postgres:18.3-alpine
    volumes:
      - ./database/data:/var/lib/postgresql/18/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

